Update IJEMortality.cs
nightingaleproject/vrdr-dotnet pull request #429
Opened 2023-05-18 15:29 UTC by consultantusa

2023-05-19 17:13 UTC, johnarleyburns requested changes
Please add test case for these exceptions.

2023-05-19 17:13 UTC, johnarleyburns requested changes
Please add test case for these exceptions.

2023-05-30 20:47 UTC, consultantusa commented
Added test case. Thank you.

2023-05-31 17:16 UTC, johnarleyburns approved these changes

2023-05-31 17:16 UTC, merged